 format = """
 $directory\
 [î‚´](fg:hyacinth_blue bg:navy_blue)\
 $git_branch\
 $git_status\
 [î‚´](fg:navy_blue bg:black)\
 $nodejs\
 $rust\
 $golang\
 $php\
 $java\
 $scala\
 [î‚°](fg:black)\
 $status\
 $line_break
 $character"""
 
 palette = 'blue_theme'
 
 [palettes.blue_theme]
 day_dream = "#a3aed2"
 hyacinth_blue = "#769ff0"
 navy_blue = "#394260"
 silver_white = "#e3e5e5"
 
 lime = "#00ff00"
 red = "#ff0000"
 black = "#212736"
 
 [line_break]
 disabled = true
 
 [directory]
 style = "fg:silver_white bg:hyacinth_blue"
 format = "[ ï“” $path ]($style)"
 truncation_length = 5
 truncate_to_repo = false
 truncation_symbol = "â€¦/"
 read_only = "ğŸ”’"
 
 [directory.substitutions]
 "Documents" = "ó°ˆ™ "
 "Downloads" = "ï€™ "
 "Music" = "ï€ "
 "Pictures" = "ï€¾ "
 
 [git_branch]
 symbol = "ï˜"
 style = "bg:navy_blue"
 format = '[[ $symbol $branch ](fg:hyacinth_blue bg:navy_blue)]($style)'
 
 [git_status]
 style = "bg:navy_blue"
 format = '[[($all_status$ahead_behind )](fg:hyacinth_blue bg:navy_blue)]($style)'
 
 [nodejs]
 symbol = "îœ˜"
 style = "bg:black"
 format = '[[ $symbol ($version) ](fg:hyacinth_blue bg:black)]($style)'
 
 [php]
 symbol = "î˜ˆ"
 style = "bg:black"
 format = '[[ $symbol ($version) ](fg:hyacinth_blue bg:black)]($style)'
 
 [java]
 symbol = "ó°¬·"
 style = "bg:black"
 format = '[[ $symbol ($version) ](fg:hyacinth_blue bg:black)]($style)'
 
 [scala]
 symbol = "îœ·"
 style = "bg:black"
 format = '[[ $symbol ($version) ](fg:hyacinth_blue bg:black)]($style)'
 
 [docker_context]
 symbol = "ïŒˆ"
 style = "bg:#black"
 format = '[[ $symbol( $context) ](fg:hyacinth_blue bg:black)]($style)'
 
 [status]
 style = "fg:#a6e3a1"
 format = '[$symbol]($style)'
 disabled = false
 success_symbol = "[ ğŸ˜»]($style)"
 symbol = "[ ğŸ˜¿](bold fg:red)"
 
 [character]
 success_symbol = '[â¯](bold fg:lime)'
 error_symbol = '[â¯](bold fg:red)'

